# Generated by Django 4.1.2 on 2022-10-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalcategory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='goalcategory',
            name='updated',
        ),
    ]
