name: Build adnd deploy
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: code clone
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t mkaprenko/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker logout
        run: docker logout
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push mkaprenko/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID